export const data = [
    {
        question: "You’re the “go-to person” among your friends for kjlednakjnsakldfmasl kladnfklajnflkasnflasnvasn aslknasknfklsalnf ansfl knfkn alksn fsnflns lfnsalknf anflaknfanlfnasl nflnlknflansflan flanflk",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },
    {
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },
    {
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },
    {
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },
    {
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },
    {
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },
    {
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },
    {
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    },{
        question: "You’re the “go-to person” among your friends for…",
        option_a:" Fixing their phones, apps, or laptops",
        option_b:" Designing posters, memes, or creative projects",
        option_c:" Explaining tricky problems or analyzing data.",
        option_d:"Writing cool captions or managing social media profiles.",
        option_e:" Helping them protect their accounts and devices.",
    }
]